stages:
  - check
  - package
  - release

default:
  tags:
    - trusted
    - shell
    - gnome

lint:
  stage: check
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  script:
    - npm ci
    - npx eslint --config .eslintrc.json .

build:
  stage: check
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'
  script:
    - meson setup build --wipe
    - meson compile -C build

package:
  stage: package
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^Gtk4-[0-9]+(\.[0-9]+)*$/'
    - if: '$CI_COMMIT_TAG =~ /^Gtk4-[0-9]+(\.[0-9]+)*\.LATEST$/'
  script:
    - VERSION="$CI_COMMIT_TAG" COMMIT_SHA="$CI_COMMIT_SHA" ./scripts/package.sh
  artifacts:
    paths:
      - dist/*
    expire_in: never

release:
  stage: release
  needs:
    - job: package
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^Gtk4-[0-9]+(\.[0-9]+)*$/'
  script:
    - echo "Creating release $CI_COMMIT_TAG"
  release:
    tag_name: "$CI_COMMIT_TAG"
    name: "$CI_PROJECT_NAME $CI_COMMIT_TAG"
    description: "Release $CI_COMMIT_TAG"
    assets:
      links:
        - name: "Built packages"
          url: "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/browse/dist?job=package"
