Libadwaita, Gtk4 Desktop Icons NG with GSconnect Integration, Drag and Drop onto Dock (Gtk4-DING)

Libadwaita/Gtk4 Port of Desktop Icons NG with updated and modified code base, uses gio menus, all functions are async where possible, multiple fixes and new features-

* New - Sets correct hovering behaviour during drag and drop on the Dock, enables scrolling to icons when they are hidden.
* Fix - unlimited workspaces, now works correctly even with auto-move-windows. More optimal and minimal shell overrides.
* New - Help with translation link in about pance of preferences. Multiple other fixes, including using old libAdwaita on Ubuntu Jammy.
* New - tool tips are now positioned correctly to not go under the dash or make it autohide, or go over any gnome shell actors on the edge of the screen.
* New - About panel preferences page that shows the correct version of the extension and weblinks to gitlab website.
* New Drag Navigation on Dock - dragging an icon over the Gnome Files icon on the dock or mounted drives, and hovering over it for 1/2 seconds will open a Gnome Files Window.
* New - Set the correct cursor with proposed action on drop on dock, improve drop detection.
* New - Drag Navigation - dragging an icon over a folder icon or a drive icon, and then hovering over it for 1/2 seconds will open that location in Gnome Files.
* New - Drag Icon now forms a bunch of icons if multiple icons are dragged. Code from Nautilus, translated to files.
* New - Now deals correctly with appimage files on desktop.
* Now uses libadwaita.
* Make Links on Desktop with Alt button on Wayland. Does not work with X11.
* Copied/dropped/pasted files retain dropped position.
* Right Click Menus will not go under the dock.
* Better multi monitor support, preference to place icons on non primary monitor.
* GSconnect extension integration, can send files from desktop directly to mobile device.
* Drag and drop Favorite apps from Dash to Dock, Dash to Panel directly to Desktop or remove from favorites.
* Improved gesture switching of workspaces, icons appear to be on all workspaces in moving windows.
* Support for dragging icons onto the dock - Drag icons from desktop to and drop over application icon to open them with the app. Works with Dash to Dock and Dash to Panel.
* Support for dragging icons from desktop directly to Trash on Dash to Dock or to mounted volumes to copy them directly.
* Display GIMP thumbnails, even for snap and flatpack installs.

Please see Readme for full details of new features. Works best on Wayland. There is a bug in GJS on X11, please see Readme. This extension now works with some hacks, even on X11. However your mileage may vary and use with caution on X11 and report any issues.

Please report all issues on the gitlab link below, this page is not monitored. All known issues are detailed there.

Extension Homepage https://gitlab.com/smedius/desktop-icons-ng
